# Generated by Django 4.2.30 on 2026-05-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Counter_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfomodel',
            name='bmr',
            field=models.FloatField(null=True),
        ),
    ]
